import {
  DEFAULT_PINCODE_RULES,
  DEFAULT_WEIGHT_RULES,
  LOCATION_SELECTION,
  WEIGHT_DISPLAY_MODES,
} from "./pincode";

export { DEFAULT_PINCODE_RULES, DEFAULT_WEIGHT_RULES, LOCATION_SELECTION, WEIGHT_DISPLAY_MODES };

export const WIDGET_LOCATIONS = {
  PRODUCT: "PRODUCT",
  CART: "CART",
  CHECKOUT: "CHECKOUT",
};

export const WIDGET_STATUSES = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SCHEDULED: "SCHEDULED",
};

export const EVENT_TYPES = {
  IMPRESSION: "IMPRESSION",
  CLICK: "CLICK",
  ADD_TO_CART: "ADD_TO_CART",
  CONVERSION: "CONVERSION",
};

export const ACTIVITY_KINDS = {
  EVENT: "EVENT",
  REQUEST: "REQUEST",
};

export const PLACEMENT_MODES = {
  ALL_PRODUCTS: "ALL_PRODUCTS",
  COLLECTIONS: "COLLECTIONS",
  PRODUCTS: "PRODUCTS",
};

export const CART_DISPLAY_MODES = {
  PER_PRODUCT: "PER_PRODUCT",
  GENERAL: "GENERAL",
};

export const MARKET_MODES = {
  ALL: "ALL",
  SPECIFIC: "SPECIFIC",
};

export const PLACEMENT_POSITIONS = {
  DEFAULT: "DEFAULT",
  CUSTOM: "CUSTOM",
  BELOW_ATC: "BELOW_ATC",
  ABOVE_ATC: "ABOVE_ATC",
  PRODUCT_INFO: "PRODUCT_INFO",
  CART_PAGE: "CART_PAGE",
  CART_DRAWER: "CART_DRAWER",
  BEFORE_CHECKOUT: "BEFORE_CHECKOUT",
  AFTER_ITEMS: "AFTER_ITEMS",
  CHECKOUT_BLOCK: "CHECKOUT_BLOCK",
  AFTER_SHIPPING: "AFTER_SHIPPING",
  THANK_YOU: "THANK_YOU",
};

export const ALL_PLACEMENT_POSITIONS = Object.values(PLACEMENT_POSITIONS);

export const DATE_FORMATS = {
  LONG: "LONG",
  NUMERIC_MDY: "NUMERIC_MDY",
  NUMERIC_DMY: "NUMERIC_DMY",
};

export const WORKING_DAYS = [
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
  "SATURDAY",
  "SUNDAY",
];

export const DEFAULT_WORKING_DAYS = [
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
];

export const MESSAGE_TAGS = [
  { tag: "{counter}", label: "Countdown" },
  { tag: "{delivery_from}", label: "Delivery from" },
  { tag: "{delivery_to}", label: "Delivery to" },
  { tag: "{delivery_date}", label: "Delivery date range" },
  { tag: "{processing_from}", label: "Processing from" },
  { tag: "{processing_to}", label: "Processing to" },
  { tag: "{ordered_date}", label: "Order date" },
<<<<<<< HEAD
  // { tag: "{stock_left}", label: "Stock left" },
  { tag: "{product_name}", label: "Product name" },
  // { tag: "{image}", label: "Header image" },
];

export const TRANSLATION_LOCALES = [
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "es", label: "Spanish" },
  { value: "it", label: "Italian" },
  { value: "pt", label: "Portuguese" },
  { value: "nl", label: "Dutch" },
  { value: "da", label: "Danish" },
  { value: "sv", label: "Swedish" },
  { value: "nb", label: "Norwegian" },
  { value: "fi", label: "Finnish" },
  { value: "ja", label: "Japanese" },
=======
  { tag: "{product_name}", label: "Product name" },
>>>>>>> 64a9729 (Remove deprecated components and streamline configuration files)
];

export const FONT_OPTIONS = [
  { value: "inherit", label: "Theme default" },
  { value: "Inter, sans-serif", label: "Inter" },
  { value: "Arial, sans-serif", label: "Arial" },
  { value: "Georgia, serif", label: "Georgia" },
  { value: "Times New Roman, serif", label: "Times New Roman" },
];

export const HEADING_WEIGHT_OPTIONS = [
  { value: 400, label: "Regular" },
  { value: 500, label: "Medium" },
  { value: 600, label: "Semibold" },
  { value: 700, label: "Bold" },
  { value: 800, label: "Extra bold" },
];

export const DEFAULT_SHIPPING = {
  processingMinDays: 0,
  processingMaxDays: 1,
  cutoffTime: "12:00 AM",
  workingDays: DEFAULT_WORKING_DAYS,
  blockedDates: [],
  transitMinDays: 1,
  transitMaxDays: 2,
  transitWorkingDays: DEFAULT_WORKING_DAYS,
  transitBlockedDates: [],
  pincodeRules: DEFAULT_PINCODE_RULES,
  weightRules: DEFAULT_WEIGHT_RULES,
  countryRules: {
    country: "IN",
    countries: [],
    locations: [],
    stateMode: "SPECIFIC",
    states: [],
    cityMode: "SPECIFIC",
    cities: [],
  },
};

export const DEFAULT_MESSAGE = {
  heading: "",
  template:
    "Order today within {counter}, you'll receive your package between {delivery_from} to {delivery_to}",
  dateFormat: DATE_FORMATS.LONG,
  dateSeparator: "/",
  includeYear: true,
  widgetLayout: "FULL",
  designTemplate: "TIMELINE",
  descriptionEnabled: true,
  headingEnabled: true,
  translations: {},
};

export const DEFAULT_ICONS = {
  purchased: "bag",
  processing: "truck",
  delivered: "pin",
  headerIcon: "flag",
  headerIconEnabled: true,
  purchasedEnabled: true,
  processingEnabled: true,
  deliveredEnabled: true,
  purchasedTitle: "Purchased",
  processingTitle: "Processing",
  deliveredTitle: "Delivered",
  purchasedColor: "",
  processingColor: "",
  deliveredColor: "",
  savedIcons: [],
};

export const WIDGET_DESIGNS = [
  { value: "EXPRESS", label: "Same Day", help: "Rush and local delivery with a clear countdown" },
  { value: "MOMENT", label: "Cutoff", help: "Urge shoppers to order before today’s dispatch window" },
  { value: "METER", label: "Made to Order", help: "Show crafting progress for custom goods" },
  { value: "SEGMENTS", label: "3 Steps", help: "Teach order → ship → arrive in three panels" },
  { value: "TRACKER", label: "Tracking", help: "Familiar courier-style milestones" },
  { value: "JOURNEY", label: "Doorstep", help: "Home-delivery path from pack to door" },
  { value: "TIMELINE", label: "Standard", help: "Everyday retail ETA with a classic timeline" },
  { value: "STACKED", label: "Mobile", help: "Vertical steps that stay clear on phones" },
  { value: "PILL", label: "Quick Dates", help: "Compact date chips for dense product pages" },
  { value: "BANNER", label: "Notice", help: "Subtle delivery bar that won’t dominate the PDP" },
  { value: "CARD", label: "Promise", help: "Bold delivery promise to boost buy confidence" },
  { value: "BAND", label: "Status", help: "Status-first strip for information-heavy pages" },
  { value: "BUBBLE", label: "Brand", help: "Playful track for lifestyle and DTC brands" },
  { value: "HERO", label: "Hero", help: "Large ETA headline for conversion-focused PDPs" },
  { value: "DROP", label: "Drop", help: "Highlight a release or drop delivery date" },
  { value: "CLEAN", label: "Minimal", help: "Clean single-focus ETA for quiet storefronts" },
  { value: "CHECKLIST", label: "Checklist", help: "Simple step list for clear order expectations" },
  { value: "PICKUP", label: "Pickup", help: "In-store or curbside pickup ticket style" },
  { value: "PREORDER", label: "Pre-Order", help: "Vertical rail for upcoming ship windows" },
  { value: "WHOLESALE", label: "Wholesale", help: "Split layout for B2B and bulk timelines" },
  { value: "CALENDAR", label: "Calendar", help: "Three date cards for a calendar-style glance" },
];

export const ANIMATED_DESIGNS = new Set([
  "MOMENT",
  "BUBBLE",
  "EXPRESS",
  "SEGMENTS",
  "METER",
  "BAND",
  "JOURNEY",
  "HERO",
  "DROP",
  "CLEAN",
  "CHECKLIST",
  "PICKUP",
  "PREORDER",
  "WHOLESALE",
  "CALENDAR",
]);

/** Default heading + message copy applied when a merchant picks a template. */
export const TEMPLATE_CONTENT_PRESETS = {
  EXPRESS: {
    heading: "SAME-DAY DELIVERY",
    template: "Order within {counter} to get it by {delivery_date}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  MOMENT: {
    heading: "Order before cutoff",
    template: "Order today within {counter} for delivery between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  METER: {
    heading: "Made just for you",
    template: "Your order is crafted and ships between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  SEGMENTS: {
    heading: "How delivery works",
    template: "From checkout to your door between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  TRACKER: {
    heading: "Track your order",
    template: "Estimated arrival between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  JOURNEY: {
    heading: "On the way home",
    template: "Arrives at your doorstep between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  TIMELINE: {
    heading: "Estimated delivery",
    template: "Order today within {counter}, delivery between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  STACKED: {
    heading: "Delivery timeline",
    template: "Expected between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  PILL: {
    heading: "Key dates",
    template: "Delivery window {delivery_date}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  BANNER: {
    heading: "Delivery",
    template: "Get it between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  CARD: {
    heading: "Our delivery promise",
    template: "Guaranteed window {delivery_date}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  BAND: {
    heading: "Order status",
    template: "Current estimate {delivery_date}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  BUBBLE: {
    heading: "Your delivery date",
    template: "Looks like {delivery_date} - we’ll keep you posted",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  HERO: {
    heading: "Get it by",
    template: "Order within {counter} to lock this delivery window",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  DROP: {
    heading: "Drop ships",
    template: "Reserve now - ships {delivery_date}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  CLEAN: {
    heading: "Delivery",
    template: "Arrives {delivery_date}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  CHECKLIST: {
    heading: "What happens next",
    template: "Your delivery window is {delivery_date}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  PICKUP: {
    heading: "Ready for pickup",
    template: "Collect in store between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  PREORDER: {
    heading: "Pre-order ship window",
    template: "Expected to ship between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  WHOLESALE: {
    heading: "Bulk delivery estimate",
    template: "Wholesale orders arrive between {delivery_from} and {delivery_to}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
  CALENDAR: {
    heading: "Delivery calendar",
    template: "Plan around {delivery_date}",
    descriptionEnabled: true,
    headingEnabled: true,
  },
};
<<<<<<< HEAD

export const TEMPLATE_COLORS = [
  "#000000",
  "#E53935",
  "#43A047",
  "#1E88E5",
  "#3949AB",
  "#FDD835",
  "#757575",
  "#F57C00",
  "#7C3AED",
  "#DB2777",
  "#0891B2",
  "#0F766E",
];

/** Soft backgrounds that stay readable behind widget content. */
export const BACKGROUND_COLORS = [
  "#FFFFFF",
  "#F4F6F8",
  "#F3F4F6",
  "#EFF6FF",
  "#ECFEFF",
  "#ECFDF5",
  "#FFF7ED",
  "#FFFBEB",
  "#FFF5F7",
  "#F5F3FF",
  "#F8FAFC",
  "#E8FBFC",
];
=======
>>>>>>> 64a9729 (Remove deprecated components and streamline configuration files)

export const TEMPLATE_STYLE_PRESETS = {
  TIMELINE: {
    backgroundType: "SOLID",
    backgroundColor: "#F4F6F8",
    borderWidth: 1,
    borderColor: "#D8DEE4",
    borderRadius: 14,
    iconSize: 36,
    progressWidth: 3,
    themeColor: "#1A1A1A",
    progressColor: "#1A1A1A",
    textColor: "#1A1A1A",
    statusColor: "#4A4A4A",
    dateColor: "#1A1A1A",
    dynamicColor: "#1A1A1A",
    paddingTop: 16,
    paddingMiddle: 12,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  MOMENT: {
    backgroundType: "GRADIENT",
    backgroundColor: "#FFF5F7",
    gradientStart: "#FFE4EC",
    gradientEnd: "#FFFFFF",
    gradientDirection: "TO_BOTTOM",
    borderWidth: 0,
    borderRadius: 16,
    iconSize: 40,
    progressWidth: 4,
    themeColor: "#E53935",
    progressColor: "#E53935",
    textColor: "#222222",
    statusColor: "#222222",
    dateColor: "#E53935",
    dynamicColor: "#E53935",
    paddingTop: 16,
    paddingMiddle: 14,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  BUBBLE: {
    backgroundType: "SOLID",
    backgroundColor: "#FFF0F6",
    borderWidth: 2,
    borderColor: "#F9A8D4",
    borderRadius: 18,
    iconSize: 42,
    progressWidth: 4,
    themeColor: "#BE185D",
    progressColor: "#BE185D",
    textColor: "#831843",
    statusColor: "#831843",
    dateColor: "#BE185D",
    dynamicColor: "#BE185D",
    paddingTop: 12,
    paddingMiddle: 10,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 12,
  },
  EXPRESS: {
    backgroundType: "SOLID",
    backgroundColor: "#F3F4F6",
    borderWidth: 0,
    borderRadius: 14,
    iconSize: 38,
    progressWidth: 4,
    themeColor: "#111827",
    progressColor: "#111827",
    textColor: "#111827",
    statusColor: "#111827",
    dateColor: "#111827",
    dynamicColor: "#111827",
    paddingTop: 14,
    paddingMiddle: 12,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
  },
  SEGMENTS: {
    backgroundType: "SOLID",
    backgroundColor: "#EFF6FF",
    borderWidth: 0,
    borderRadius: 14,
    iconSize: 36,
    themeColor: "#1D4ED8",
    progressColor: "#1D4ED8",
    textColor: "#1E3A8A",
    statusColor: "#1E3A8A",
    dateColor: "#1D4ED8",
    dynamicColor: "#1D4ED8",
    paddingTop: 0,
    paddingMiddle: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
  },
  METER: {
    backgroundType: "SOLID",
    backgroundColor: "#FFF7ED",
    borderWidth: 0,
    borderRadius: 18,
    iconSize: 44,
    progressWidth: 8,
    themeColor: "#C2410C",
    progressColor: "#EA580C",
    textColor: "#7C2D12",
    statusColor: "#7C2D12",
    dateColor: "#C2410C",
    dynamicColor: "#EA580C",
    paddingTop: 18,
    paddingMiddle: 14,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  BAND: {
    backgroundType: "SOLID",
    backgroundColor: "#F5F3FF",
    borderWidth: 0,
    borderRadius: 12,
    iconSize: 40,
    themeColor: "#6D28D9",
    progressColor: "#6D28D9",
    textColor: "#4C1D95",
    statusColor: "#5B21B6",
    dateColor: "#111111",
    dynamicColor: "#6D28D9",
    paddingTop: 14,
    paddingMiddle: 10,
    paddingBottom: 14,
    paddingLeft: 10,
    paddingRight: 10,
  },
  JOURNEY: {
    backgroundType: "SOLID",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 16,
    iconSize: 44,
    progressWidth: 5,
    paddingTop: 18,
    paddingMiddle: 14,
    paddingBottom: 18,
    paddingLeft: 16,
    paddingRight: 16,
    themeColor: "#0F172A",
    progressColor: "#0F172A",
    textColor: "#0F172A",
    statusColor: "#334155",
    dateColor: "#0F172A",
    dynamicColor: "#0F172A",
  },
  STACKED: {
    backgroundType: "SOLID",
    backgroundColor: "#ECFDF5",
    borderWidth: 1,
    borderColor: "#A7F3D0",
    borderRadius: 14,
    iconSize: 34,
    progressWidth: 3,
    themeColor: "#047857",
    progressColor: "#047857",
    textColor: "#064E3B",
    statusColor: "#064E3B",
    dateColor: "#047857",
    dynamicColor: "#047857",
    paddingTop: 14,
    paddingMiddle: 10,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
  },
  PILL: {
    backgroundType: "SOLID",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#99F6E4",
    borderRadius: 18,
    iconSize: 32,
    themeColor: "#0F766E",
    progressColor: "#0F766E",
    textColor: "#134E4A",
    statusColor: "#134E4A",
    dateColor: "#0F766E",
    dynamicColor: "#0F766E",
    paddingTop: 14,
    paddingMiddle: 12,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
  },
  TRACKER: {
    backgroundType: "SOLID",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    borderRadius: 14,
    iconSize: 36,
    progressWidth: 3,
    themeColor: "#1E40AF",
    progressColor: "#1E40AF",
    textColor: "#0F172A",
    statusColor: "#0F172A",
    dateColor: "#1E40AF",
    dynamicColor: "#1E40AF",
    paddingTop: 14,
    paddingMiddle: 12,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
  },
  BANNER: {
    backgroundType: "SOLID",
    backgroundColor: "#FFFBEB",
    borderWidth: 1,
    borderColor: "#FCD34D",
    borderRadius: 12,
    iconSize: 32,
    themeColor: "#B45309",
    progressColor: "#B45309",
    textColor: "#78350F",
    statusColor: "#78350F",
    dateColor: "#B45309",
    dynamicColor: "#B45309",
    paddingTop: 12,
    paddingMiddle: 10,
    paddingBottom: 12,
    paddingLeft: 14,
    paddingRight: 14,
  },
  CARD: {
    backgroundType: "SOLID",
    backgroundColor: "#ECFEFF",
    borderWidth: 2,
    borderColor: "#22D3EE",
    borderRadius: 16,
    iconSize: 38,
    themeColor: "#0E7490",
    progressColor: "#0E7490",
    textColor: "#155E75",
    statusColor: "#155E75",
    dateColor: "#0E7490",
    dynamicColor: "#0E7490",
    paddingTop: 16,
    paddingMiddle: 12,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  HERO: {
    backgroundType: "GRADIENT",
    backgroundColor: "#EFF6FF",
    gradientStart: "#DBEAFE",
    gradientEnd: "#FFFFFF",
    gradientDirection: "TO_BOTTOM",
    borderWidth: 0,
    borderRadius: 18,
    iconSize: 34,
    progressWidth: 3,
    themeColor: "#1D4ED8",
    progressColor: "#1D4ED8",
    textColor: "#1E3A8A",
    statusColor: "#1E40AF",
    dateColor: "#1D4ED8",
    dynamicColor: "#1D4ED8",
    paddingTop: 18,
    paddingMiddle: 12,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  DROP: {
    backgroundType: "SOLID",
    backgroundColor: "#18181B",
    borderWidth: 0,
    borderRadius: 16,
    iconSize: 32,
    themeColor: "#FAFAFA",
    progressColor: "#F472B6",
    textColor: "#FAFAFA",
    statusColor: "#E4E4E7",
    dateColor: "#F472B6",
    dynamicColor: "#F472B6",
    paddingTop: 16,
    paddingMiddle: 12,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  CLEAN: {
    backgroundType: "SOLID",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    iconSize: 28,
    themeColor: "#111827",
    progressColor: "#111827",
    textColor: "#111827",
    statusColor: "#6B7280",
    dateColor: "#111827",
    dynamicColor: "#111827",
    paddingTop: 14,
    paddingMiddle: 10,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
  },
  CHECKLIST: {
    backgroundType: "SOLID",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 14,
    iconSize: 30,
    progressWidth: 2,
    themeColor: "#0F766E",
    progressColor: "#0F766E",
    textColor: "#0F172A",
    statusColor: "#334155",
    dateColor: "#0F766E",
    dynamicColor: "#0F766E",
    paddingTop: 14,
    paddingMiddle: 10,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
  },
  PICKUP: {
    backgroundType: "SOLID",
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FDBA74",
    borderRadius: 14,
    iconSize: 34,
    themeColor: "#C2410C",
    progressColor: "#C2410C",
    textColor: "#7C2D12",
    statusColor: "#9A3412",
    dateColor: "#C2410C",
    dynamicColor: "#C2410C",
    paddingTop: 0,
    paddingMiddle: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
  },
  PREORDER: {
    backgroundType: "SOLID",
    backgroundColor: "#F5F3FF",
    borderWidth: 1,
    borderColor: "#DDD6FE",
    borderRadius: 16,
    iconSize: 34,
    progressWidth: 4,
    themeColor: "#6D28D9",
    progressColor: "#6D28D9",
    textColor: "#4C1D95",
    statusColor: "#5B21B6",
    dateColor: "#6D28D9",
    dynamicColor: "#6D28D9",
    paddingTop: 16,
    paddingMiddle: 12,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  WHOLESALE: {
    backgroundType: "SOLID",
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#94A3B8",
    borderRadius: 12,
    iconSize: 32,
    progressWidth: 3,
    themeColor: "#334155",
    progressColor: "#334155",
    textColor: "#0F172A",
    statusColor: "#475569",
    dateColor: "#0F172A",
    dynamicColor: "#0F172A",
    paddingTop: 14,
    paddingMiddle: 10,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
  },
  CALENDAR: {
    backgroundType: "SOLID",
    backgroundColor: "#ECFDF5",
    borderWidth: 1,
    borderColor: "#6EE7B7",
    borderRadius: 16,
    iconSize: 30,
    themeColor: "#047857",
    progressColor: "#047857",
    textColor: "#064E3B",
    statusColor: "#065F46",
    dateColor: "#047857",
    dynamicColor: "#047857",
    paddingTop: 14,
    paddingMiddle: 10,
    paddingBottom: 14,
    paddingLeft: 12,
    paddingRight: 12,
  },
};

export const TEMPLATE_TITLE_PRESETS = {
  EXPRESS: {
    purchased: "bag",
    processing: "truck",
    delivered: "pin",
    headerIcon: "clock",
    headerIconEnabled: true,
    purchasedTitle: "Ordered",
    processingTitle: "Out for delivery",
    deliveredTitle: "Delivered today",
  },
  MOMENT: {
    purchased: "bag",
    processing: "truck",
    delivered: "pin",
    headerIconEnabled: false,
    purchasedTitle: "Order by",
    processingTitle: "Dispatch",
    deliveredTitle: "Delivered",
  },
  METER: {
    purchased: "package",
    processing: "box",
    delivered: "truck",
    headerIconEnabled: false,
    purchasedTitle: "Ordered",
    processingTitle: "Crafting",
    deliveredTitle: "Ships",
  },
  SEGMENTS: {
    purchased: "bag",
    processing: "truck",
    delivered: "home",
    headerIconEnabled: false,
    purchasedTitle: "You order",
    processingTitle: "We ship",
    deliveredTitle: "You receive",
  },
  TRACKER: {
    purchased: "check",
    processing: "truck",
    delivered: "home",
    headerIcon: "flag",
    headerIconEnabled: true,
    purchasedTitle: "Confirmed",
    processingTitle: "In transit",
    deliveredTitle: "Delivered",
  },
  JOURNEY: {
    purchased: "package",
    processing: "truck",
    delivered: "home",
    headerIcon: "home",
    headerIconEnabled: false,
    purchasedTitle: "Packed",
    processingTitle: "On the road",
    deliveredTitle: "At your door",
  },
  TIMELINE: {
    purchased: "bag",
    processing: "truck",
    delivered: "home",
    headerIconEnabled: false,
    purchasedTitle: "Ordered",
    processingTitle: "Shipping",
    deliveredTitle: "Arrives",
  },
  STACKED: {
    purchased: "package",
    processing: "truck",
    delivered: "pin",
    headerIconEnabled: false,
    purchasedTitle: "Placed",
    processingTitle: "In transit",
    deliveredTitle: "Arrives",
  },
  PILL: {
    purchased: "calendar",
    processing: "truck",
    delivered: "check",
    headerIconEnabled: false,
    purchasedTitle: "Order",
    processingTitle: "Ship",
    deliveredTitle: "Arrive",
  },
  BANNER: {
    purchased: "clock",
    processing: "truck",
    delivered: "pin",
    headerIcon: "clock",
    headerIconEnabled: true,
    purchasedTitle: "Ordered",
    processingTitle: "Shipped",
    deliveredTitle: "Delivered",
  },
  CARD: {
    purchased: "package",
    processing: "truck",
    delivered: "pin",
    headerIcon: "check",
    headerIconEnabled: true,
    purchasedTitle: "Ordered",
    processingTitle: "Shipped",
    deliveredTitle: "Delivered",
  },
  BAND: {
    purchased: "calendar",
    processing: "truck",
    delivered: "bag",
    headerIconEnabled: false,
    purchasedTitle: "Ordered",
    processingTitle: "Processing",
    deliveredTitle: "Ready",
  },
  BUBBLE: {
    purchased: "package",
    processing: "truck",
    delivered: "bag",
    headerIcon: "bag",
    headerIconEnabled: true,
    purchasedTitle: "Yours",
    processingTitle: "Shipping",
    deliveredTitle: "With you",
  },
  HERO: {
    purchased: "bag",
    processing: "truck",
    delivered: "home",
    headerIconEnabled: false,
    purchasedTitle: "Order",
    processingTitle: "Ship",
    deliveredTitle: "Arrive",
  },
  DROP: {
    purchased: "flag",
    processing: "package",
    delivered: "truck",
    headerIcon: "flag",
    headerIconEnabled: true,
    purchasedTitle: "Reserved",
    processingTitle: "Packed",
    deliveredTitle: "Ships",
  },
  CLEAN: {
    purchased: "bag",
    processing: "truck",
    delivered: "pin",
    headerIconEnabled: false,
    purchasedTitle: "Ordered",
    processingTitle: "Shipped",
    deliveredTitle: "Arrives",
  },
  CHECKLIST: {
    purchased: "check",
    processing: "truck",
    delivered: "home",
    headerIconEnabled: false,
    purchasedTitle: "Order placed",
    processingTitle: "In transit",
    deliveredTitle: "Delivered",
  },
  PICKUP: {
    purchased: "bag",
    processing: "package",
    delivered: "pin",
    headerIcon: "pin",
    headerIconEnabled: true,
    purchasedTitle: "Ordered",
    processingTitle: "Prepared",
    deliveredTitle: "Ready",
  },
  PREORDER: {
    purchased: "calendar",
    processing: "box",
    delivered: "truck",
    headerIcon: "calendar",
    headerIconEnabled: true,
    purchasedTitle: "Reserved",
    processingTitle: "Producing",
    deliveredTitle: "Ships",
  },
  WHOLESALE: {
    purchased: "box",
    processing: "truck",
    delivered: "home",
    headerIcon: "box",
    headerIconEnabled: true,
    purchasedTitle: "Confirmed",
    processingTitle: "Fulfilled",
    deliveredTitle: "Delivered",
  },
  CALENDAR: {
    purchased: "calendar",
    processing: "truck",
    delivered: "check",
    headerIcon: "calendar",
    headerIconEnabled: false,
    purchasedTitle: "Order day",
    processingTitle: "Ship day",
    deliveredTitle: "Arrive day",
  },
};

export const EDITOR_TABS = [
  { id: "conditions", label: "Conditions" },
  { id: "design", label: "Design" },
  { id: "placement", label: "Placement" },
];

export const ICON_OPTIONS = [
  { value: "package", label: "Package", polaris: "package" },
  { value: "box", label: "Box", polaris: "product" },
  { value: "truck", label: "Truck", polaris: "delivery" },
  { value: "clock", label: "Clock", polaris: "clock" },
  { value: "calendar", label: "Calendar", polaris: "calendar" },
  { value: "check", label: "Check", polaris: "check-circle" },
  { value: "home", label: "Home", polaris: "home" },
  { value: "pin", label: "Pin", polaris: "location" },
  { value: "bag", label: "Shopping bag", polaris: "cart" },
  { value: "flag", label: "Flag", polaris: "flag" },
];

export const ANIMATED_ICON_OPTIONS = [
  { value: "animTruck", label: "Truck drive", base: "truck", motion: "drive" },
  { value: "animPackage", label: "Package bounce", base: "package", motion: "bounce" },
  { value: "animBox", label: "Box shake", base: "box", motion: "shake" },
  { value: "animClock", label: "Clock tick", base: "clock", motion: "tick" },
  { value: "animBag", label: "Bag float", base: "bag", motion: "float" },
  { value: "animPin", label: "Pin drop", base: "pin", motion: "drop" },
  { value: "animCheck", label: "Check pop", base: "check", motion: "pop" },
  { value: "animHome", label: "Home bob", base: "home", motion: "bob" },
  { value: "animFlag", label: "Flag wave", base: "flag", motion: "wave" },
  { value: "animCalendar", label: "Calendar flip", base: "calendar", motion: "flip" },
];

export const ANIMATED_ICON_MAP = Object.fromEntries(
  ANIMATED_ICON_OPTIONS.map((item) => [item.value, item]),
);

export const GRADIENT_DIRECTIONS = [
  { value: "TO_RIGHT", label: "Left to right" },
  { value: "TO_LEFT", label: "Right to left" },
  { value: "TO_BOTTOM", label: "Top to bottom" },
  { value: "TO_TOP", label: "Bottom to top" },
  { value: "TO_BOTTOM_RIGHT", label: "Diagonal down" },
];

export const DEFAULT_STYLE = {
  backgroundType: "SOLID",
  backgroundColor: "#E8E8E8",
  gradientStart: "#FFFFFF",
  gradientEnd: "#F1F1F1",
  gradientDirection: "TO_BOTTOM",
  borderRadius: 8,
  themeColor: "#000000",
  borderWidth: 0,
  borderColor: "#E1E3E5",
  paddingTop: 16,
  paddingMiddle: 12,
  paddingBottom: 12,
  paddingLeft: 16,
  paddingRight: 16,
  iconSize: 22,
  progressWidth: 2,
  progressColor: "#000000",
  fontFamily: "inherit",
  fontSize: 15,
  textColor: "#202223",
  statusFontSize: 13,
  statusColor: "#202223",
  dateFontSize: 13,
  dateColor: "#202223",
  dynamicColor: "#202223",
  headingFontWeight: 600,
  customCss: "",
  elementStyles: {},
};

export const DEFAULT_PLACEMENT = {
  mode: PLACEMENT_MODES.ALL_PRODUCTS,
  productIds: [],
  collectionIds: [],
  products: [],
  collections: [],
  position: PLACEMENT_POSITIONS.DEFAULT,
};

export const DEFAULT_CART = {
  displayMode: CART_DISPLAY_MODES.GENERAL,
};

export const DEFAULT_CHECKOUT = {
  heading: "Estimated Delivery",
  template:
    "You'll receive your package between {delivery_from} to {delivery_to}",
  purchasedIcon: "check",
  processingIcon: "clock",
  deliveredIcon: "truck",
  backgroundType: "SOLID",
  backgroundColor: "#FFFFFF",
  gradientStart: "#FFFFFF",
  gradientEnd: "#F1F1F1",
  gradientDirection: "TO_BOTTOM",
  borderRadius: 8,
  themeColor: "#008060",
};

export function locationLabel(location) {
  if (location === WIDGET_LOCATIONS.CART) return "Cart page";
  if (location === WIDGET_LOCATIONS.CHECKOUT) return "Checkout page";
  return "Product page";
}

export function defaultWidgetName(location) {
  if (location === WIDGET_LOCATIONS.CART) return "New cart delivery widget";
  if (location === WIDGET_LOCATIONS.CHECKOUT) return "New checkout delivery widget";
  return "New estimated delivery widget";
}

export function defaultPosition(location) {
  if (location === WIDGET_LOCATIONS.CART) return PLACEMENT_POSITIONS.CART_PAGE;
  if (location === WIDGET_LOCATIONS.CHECKOUT) return PLACEMENT_POSITIONS.CHECKOUT_BLOCK;
  return PLACEMENT_POSITIONS.BELOW_ATC;
}
